// /**
//  * Curated product links for each section of the landing page.
//  * These links are fetched from the backend and displayed in the exact order specified.
//  */

import { shuffleArray } from '../utils/shuffleArray';

export const NEW_THIS_WEEK_LINKS = [
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-kent-hand-tailored-velvet-jacket-prod285470384',
 
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-suede-overshirt-prod282630097',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-shoulder-womens-bag-4',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-womens-handbag',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-silk-satin-button-down-shirt-prod193920258',
  
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cotton-velvet-shawl-lapel-sport-coat-prod285600538',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-textured-wool-notch-lapel-sport-coat-prod194790326',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-brushed-cashmere-twill-blazer-prod285600690',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-gregory-hand-tailored-velvet-dinner-jacket-prod285470192','https://www.bergdorfgoodman.com/p/brunello-cucinelli-wool-flannel-wide-leg-ankle-cargo-pants-prod193920181',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-silk-satin-button-down-shirt-prod282310146',
  'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-leather-boots-item-23688718.aspx',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-embellished-button-dress?ID=5634850&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-crystal-button-front-tweed-midi-dress-with-belt-prod196640370',
  'https://www.neimanmarcus.com/p/carolina-herrera-crystal-button-front-tweed-midi-dress-with-belt-prod284810191',
  'https://www.bergdorfgoodman.com/p/kiton-mens-baba-cotton-and-silk-side-pocket-overshirt-prod193330109',
  'https://www.farfetch.com/in/shopping/men/brioni-suede-loafers-item-29083290.aspx',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-cutout-embroidered-tweed-mini-dress-prod192590354',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-cherry-blossom-jacquard-ombre-dress-prod192590366',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-crystal-embroidered-short-sleeve-mini-cocktail-dress-prod192600084',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-butterfly-faille-bustier-tea-length-dress-prod192590344',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-single-breasted-linen-blazer-item-23608291.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-metallic-double-pocket-blouse-prod198320210',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-monili-fan-earrings-prod193920125',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-logo-embossed-messenger-bag-item-28450299.aspx',
  'https://www.farfetch.com/in/shopping/men/canali-single-breasted-blazer-item-25708437.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-felpa-jersey-safari-jacket-prod198320302',
  'https://www.bergdorfgoodman.com/p/kiton-printed-silk-midi-shirtdress-prod193900314',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-tiered-multi-strand-drop-earrings-prod279610256',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-felpa-jersey-safari-jacket-prod282251100',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-one-shoulder-silk-drape-dress?ID=5652420&CategoryID=1065659',
  'https://www.shopsimon.com/products/wanda-mini-stain-and-strass-top-handle-bag',
  'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-cotton-zip-up-hoodie-item-31433795.aspx',
  'https://www.shopsimon.com/products/wanda-mini-stain-and-strass-top-handle-bag-1',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-stretch-satin-button-front-blouse-prod282280051',
  'https://www.shopsimon.com/products/salvatore-ferragamo-leather-shoulder-womens-bag-1',
  'https://www.bloomingdales.com/shop/product/canali-siena-screenweave-solid-regular-fit-suit?ID=5147244&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/canali-siena-screenweave-regular-fit-suit?ID=5442099&CategoryID=1065659',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-logo-plaque-shoulder-bag-item-19172297.aspx',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-buttoned-cardigan-item-31984028.aspx',
  'https://www.farfetch.com/in/shopping/men/canali-checked-blazer-item-27816109.aspx',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-ribbed-knit-cotton-polo-shirt-item-22057127.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mohair-cozy-candy-floss-knit-crewneck-sweater-prod193920045',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-metallic-cashmere-silk-mock-neck-top-prod285280338',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sparkling-cashmere-winter-vanise-crewneck-sweater-prod193920011',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sequined-english-rib-sweater-prod192250092',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-sparkly-zip-jacket-prod282310098',
];
export const DESIGNER_SALE_LINKS_SET = [
  'https://www.shopsimon.com/products/sonya-leather-platform-sandals',
  'https://www.bloomingdales.com/shop/product/tom-ford-sabrina-square-sunglasses-58mm?ID=3510361&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cashmere-blend-hybrid-down-sweater-prod285470328',
  'https://www.shopsimon.com/products/single-breasted-blazer-27',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-city-suede-knee-high-boots-prod193990083',
  'https://www.bloomingdales.com/shop/product/tom-ford-raven-square-sunglasses-60mm?ID=4689531&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-one-shoulder-silk-drape-dress?ID=5652420&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-plaid-modern-fit-sport-shirt-prod196810991',
  'https://www.bergdorfgoodman.com/p/kiton-mens-baba-cotton-and-silk-side-pocket-overshirt-prod193330109',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-stripe-cotton-jute-open-knit-short-sleeve-sweater-prod198320592',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-crystal-two-drop-earrings-prod198360099',
  'https://www.shopsimon.com/products/oreste-leather-bootie',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-lightweight-denim-western-shirt-prod194080054',
  'https://www.shopsimon.com/products/beaded-embroidery-open-front-wool-blazer-in-black',
  'https://www.bergdorfgoodman.com/p/kiton-mens-wool-plaid-snap-front-overshirt-prod198320699',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-calfskin-leather-loafer-mules-prod286670446',
  // 'https://www.ssense.com/en-us/men/product/brioni/off-white-cotton-gabardine-shorts/17104851',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-collared-halter-midi-dress?ID=5520041&CategoryID=1065659',
  'https://www.shopsimon.com/products/chic-jacquard-blazer-in-navy',
  'https://www.shopsimon.com/products/bear-cotton-long-sleeve-pajama-set-in-snowfall-blue',
  // 'https://www.ssense.com/en-us/men/product/bottega-veneta/brown-bv1393s-sunglasses/17798701',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-sleeveless-floral-ruffle-dress-prod193310145',
  'https://www.shopsimon.com/products/straight-leg-wool-trousers-2',
  'https://www.shopsimon.com/products/loreno-chelsea-boots-1',
  'https://www.bloomingdales.com/shop/product/etro-long-sleeve-gown?ID=5570297&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/kiton-fitted-wool-blazer-prod193910059',
  'https://www.bergdorfgoodman.com/p/kiton-plaid-button-down-wool-cashmere-shirt-prod193900228',
  'https://www.shopsimon.com/products/mens-penny-slot-leather-loafers-in-green',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-wool-flannel-waist-tab-double-pleated-pants-prod285470368',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-plaid-viscose-blend-midi-skirt-prod284850035',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-ribbed-wool-cashmere-drawstring-pants-prod282310208',
  'https://www.shopsimon.com/products/oscar-de-la-renta-blouse',
  'https://www.shopsimon.com/products/oscar-de-la-renta-fringed-cape-wool-midi-dress',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-bicolor-off-shoulder-midi-dress-prod196640030',
  'https://www.shopsimon.com/products/ferragamo-pampero-suede-bootie-1',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-kent-glen-plaid-linen-and-mulberry-silk-sport-coat-prod282620314',
  'https://www.bloomingdales.com/shop/product/etro-velvet-flared-leg-pants?ID=5694543&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-cashmere-scarf-prod197330100',
  'https://www.bloomingdales.com/shop/product/dolce-gabbana-dg4446b-square-sunglasses-53mm?ID=4883776&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/tom-ford-alberto-square-sunglasses-55mm?ID=4868664&CategoryID=1065659',
  'https://www.shopsimon.com/products/elimo-lace-up-leather-boots-1',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-leather-monili-buckle-wedge-espadrilles-prod192090092',
  'https://www.shopsimon.com/products/womens-sweater-with-silk-inserts-in-white',
  // 'https://www.ssense.com/en-us/men/product/bottega-veneta/brown-round-sunglasses/17683871',
  'https://www.shopsimon.com/products/deva-sandals-6',
  'https://www.shopsimon.com/products/mens-suede-desert-boots-in-dark-blue',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-plexy-flowers-bouquet-earrings-prod198370072',
  'https://www.shopsimon.com/products/womens-crystal-embellished-sandals-in-black',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-floral-embroidered-handkerchief-midi-dress-prod194420108',
  'https://www.bergdorfgoodman.com/p/etro-long-sleeve-paisley-print-shirt-prod194070121',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-suede-cashmere-lined-gloves-prod281640225',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-city-suede-ankle-boots-prod281860185',
  'https://www.shopsimon.com/products/team-usa-closing-ceremony-polo-shirt-in-white',
  'https://www.shopsimon.com/products/polo-ralph-lauren-heritage-jeans-mens-blue-denim-straight-fit-retro-fts169',
  'https://www.shopsimon.com/products/womens-chunky-leather-biker-boots-in-black',
  'https://www.neimanmarcus.com/p/carolina-herrera-sheer-turtleneck-sweater-prod284850070',
  // 'https://www.shopsimon.com/products/womens-vara-bow-flat-sandals-in-black',
  'https://www.bloomingdales.com/shop/product/canali-impeccabile-wool-flannel-regular-fit-five-pocket-pants?ID=5536141&CategoryID=1065659',
  // 'https://www.shopsimon.com/products/womens-logo-plaque-detail-sandals-in-black',
  // 'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-solid-cotton-bow-tie-prod285470049',
  'https://www.shopsimon.com/products/ferragamo-acetate-mens-sunglasses-14',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-waffle-knit-polo-sweater-prod194790446',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-crystal-disc-triple-earrings-prod191280196',
  'https://www.neimanmarcus.com/p/carolina-herrera-floral-jacquard-midi-skirt-prod284850006',
  'https://www.shopsimon.com/products/carolina-herrera-womens-57mm-black-nude-sunglasses',
  'https://www.shopsimon.com/products/carolina-herrera-cz-flower-necklace-1',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mock-neck-nordic-cashmere-sweater-prod282250998',
  'https://www.shopsimon.com/products/carolina-herrera-off-shoulder-pleated-tulle-ruffle-gown-1',
  'https://www.bloomingdales.com/shop/product/etro-printed-cotton-dress?ID=5570296&CategoryID=1065659',
  'https://www.shopsimon.com/products/idillio-leather-watch-2',
  'https://www.shopsimon.com/products/turchina-archive-limited-edition-1960s-ballet-flats',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-cotton-flat-knit-henley-shirt-prod281640214',
  'https://www.bloomingdales.com/shop/product/tom-ford-maxwell-pilot-sunglasses-59mm?ID=4742281&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-fringe-tassel-earrings-prod198490041',
  'https://www.shopsimon.com/products/off-the-shoulder-drape-cocktail-dress-in-black',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-crystal-wave-earrings-prod283220135',
  'https://www.bloomingdales.com/shop/product/etro-shorts-swim-cover-up?ID=5570322&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-stretch-corduroy-pants-prod285620003',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-wool-and-cashmere-flecked-chevron-suit-prod281640241',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-sequined-tweed-jacket?ID=5534765&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-tulip-embellished-wool-silk-sweater-prod196640016',
  'https://www.neimanmarcus.com/p/etro-sequined-neck-silk-cashmere-tank-top-prod282180002',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-acid-wash-straight-leg-ankle-boyfriend-jeans-prod193920168',
  // 'https://www.ssense.com/en-us/men/product/bottega-veneta/gold-sardine-aviator-sunglasses/17708791',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-strapless-pleated-butterfly-poplin-ankle-dress-with-belt-prod192590299',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-solid-cotton-bow-tie-prod285470315',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-chevron-raglan-sleeve-overcoat-prod194070179',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cotton-plaid-double-pocket-button-down-shirt-prod196690083',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-draped-flower-bootcut-pants-prod196620095',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-leather-blazer-prod198330119',
  'https://www.shopsimon.com/products/air-lug-slides',
  'https://www.neimanmarcus.com/p/carolina-herrera-off-the-shoulder-ruched-gown-prod284120163',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-plaid-sweater-skirt-prod284850042',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-stewart-leather-single-breasted-sport-coat-prod285600559',
  'https://www.shopsimon.com/products/henley-wide-leg-sleep-set-in-heather-grey',
  'https://www.shopsimon.com/products/mens-rebel-sneakers-with-logo-in-black',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-high-summer-capsule-suede-full-zip-hooded-jacket-prod286880704',
  'https://www.neimanmarcus.com/p/carolina-herrera-floral-silk-belted-long-sleeve-trench-gown-prod284850080',
  'https://www.bloomingdales.com/shop/product/gucci-fashion-show-square-sunglasses-53mm?ID=5372996&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-tick-weave-harris-tweed-jacket-prod285620127',
  'https://www.bloomingdales.com/shop/product/dolce-gabbana-womens-wedge-sandals?ID=5545435&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-essense-monili-suede-clutch-bag-prod193530151',
  'https://www.shopsimon.com/products/three-quarter-bateau-neck-poplin-dress-in-navy-multi',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-framed-oval-crystal-bracelet-prod283230035',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-solid-cotton-bow-tie-prod196690001',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-honey-comb-sequin-knit-jacket?ID=5534810&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-kent-two-button-notch-lapel-sport-coat-prod194790152',
  'https://www.shopsimon.com/products/ellas-x5-caged-mules-5',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-embroidered-crewneck-sweater?ID=5634844&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-short-sleeve-cutout-hem-tweed-mini-dress-with-belt-prod192590342',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-essense-bead-embroidered-suede-clutch-bag-prod192460028',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-off-the-shoulder-floral-gathered-body-con-dress-prod193310112',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-leather-monili-penny-loafers-prod192090094',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-faux-pearl-eyelet-dress?ID=5399036&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-crystal-scramble-bracelet-prod193940168',
  'https://www.shopsimon.com/products/mens-gancini-driver-moccasins-in-black',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-pave-drop-earrings-prod192640052',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-exclusive-velvet-prod287440043',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-the-iconic-cashmere-cable-knit-crewneck-sweater-prod285620250',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-ruched-polo-dress?ID=5565450&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/carolina-herrera-embroidered-tweed-collection-prod285220016',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-wide-leg-pants?ID=5520037&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/etro-mens-paisley-stretch-sport-shirt-prod287140498',
  'https://www.shopsimon.com/products/womens-ankle-length-trousers-in-red',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-button-down-cotton-twill-shirt-prod281570054',
  'https://www.bloomingdales.com/shop/product/canali-siena-crepe-weave-windowpane-regular-fit-suit?ID=5536145&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-wool-felt-fedora-with-leather-and-monili-band-prod282440026',
  'https://www.shopsimon.com/products/womens-viva-ballerina-shoes-in-white',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-belted-midi-dress?ID=5565461&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-button-front-poplin-shirt-with-monili-pocket-prod198320158',
  'https://www.ssense.com/en-us/men/product/brioni/navy-elba-trousers/17072711',
  'https://www.bergdorfgoodman.com/p/kiton-mens-full-zip-blazer-prod198320931',
  'https://www.shopsimon.com/products/organza-plaid-check-midi-dress',
  'https://www.shopsimon.com/products/carolina-herrera-womens-53-mm-black-opticals',
  'https://www.neimanmarcus.com/p/etro-textured-tweed-top-coat-prod285740169',
  'https://www.shopsimon.com/products/jersey-short-sleeve-pajama-set-in-white-cloud',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-shoulder-womens-bag-4',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-geometric-floral-sport-shirt-prod198321033',
  'https://www.neimanmarcus.com/p/carolina-herrera-embellished-tweed-shift-dress-prod284920021',
  'https://www.shopsimon.com/products/etro-embroidered-skinny-jean',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-triple-drop-flower-earrings-prod286730794',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-wool-monili-leather-penny-loafers-prod192080190',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-the-ralph-jersey-t-shirt-prod285620343',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sparkling-cashmere-winter-vanise-crewneck-sweater-prod193920011',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-wool-double-brea-prod287440240',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-straight-leg-cotton-trousers-prod282310026',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-the-eastham-quilted-jacket-prod285620109',
  'https://www.shopsimon.com/products/oscar-de-la-renta-sweater-3',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-embellished-plunging-halter-column-gown-prod196640132',
  'https://www.shopsimon.com/products/womens-erica-slingbacks-satin-with-asymmetric-bow-pump-in-black',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-embellished-midi-dress?ID=5565448&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-crystal-four-drop-earrings-prod286730971',
  'https://www.bloomingdales.com/shop/product/etro-flared-leg-jeans-in-burgundy-print?ID=5700089&CategoryID=1065659',
  'https://www.shopsimon.com/products/sabrina-mirrored-platform-heels-1',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-glen-plaid-flat-front-trousers-prod282620154',
  'https://www.shopsimon.com/products/pleated-silk-skirt-in-black-white',
  'https://www.shopsimon.com/products/oscar-de-la-renta-wide-leg-jean',
  'https://www.bloomingdales.com/shop/product/etro-wool-paisley-trumpet-skirt?ID=5694553&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-traditional-fit-wool-overcoat-prod198321294',
  'https://www.shopsimon.com/products/eurialo-f-leather-boots',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-flower-embroidered-denim-sleeveless-maxi-dress-prod286550044',
  'https://www.bloomingdales.com/shop/product/canali-kei-wool-silk-linen-herringbone-unstructured-trim-fit-sport-coat?ID=5536129&CategoryID=1065659',
  'https://www.shopsimon.com/products/etro-reiki-mini-dress',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-satin-maxi-trumpet-skirt-prod282280278',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-fluid-wool-crepe-pants-prod282310250',
  'https://www.shopsimon.com/products/contrast-stitch-knit-dress',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sparkling-cashmere-mohair-crewneck-sweater-prod193920032',
  'https://www.bergdorfgoodman.com/p/kiton-mens-small-paisley-silk-tie-prod193860154',
  'https://www.shopsimon.com/products/english-rose-jacquard-fit-and-flare-knit-dress-in-pink-blush-peony',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-paillette-striped-hooded-sweatshirt-prod279610308',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-80mm-monili-suede-espadrille-wedge-sandals-prod286830119',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-kent-hand-tailored-glen-plaid-suit-prod285470416',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-strapless-cherry-blossom-embroidered-gown-prod192590287',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-gregory-modern-flat-front-trousers-prod194800119',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-pair-of-loafers-prod287440034',
  'https://www.shopsimon.com/products/dolce-gabbana-mens-45mm-brown-sunglasses',
  'https://www.bergdorfgoodman.com/p/kiton-mens-linen-coral-print-stretch-pants-prod198320307',
  // 'https://www.neimanmarcus.com/p/bottega-veneta-silk-midi-dress-with-adjustable-sleeves-prod284580121',
  'https://www.shopsimon.com/products/altaire-strappy-mules-1',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-paillette-striped-hooded-sweatshirt-prod198320310',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-micro-checked-ho-prod287450091',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-stretch-silk-satin-track-trousers-prod282310099',
  'https://www.shopsimon.com/products/tom-ford-womens-50mm-shiny-black-sunglasses-ft1157-01a-50',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-sequined-silk-organza-short-sleeve-mini-dress-prod282310108',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-custom-slim-pique-polo-shirt-prod192930031',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-butterfly-print-tank-top?ID=5534760&CategoryID=1065659',
  'https://www.shopsimon.com/products/womens-buckle-detail-leather-loafers-in-black',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-cotton-english-rib-half-zip-sweater-prod285271545',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-suede-equestrian-boots-with-monili-riding-detail-prod194000078',
  'https://www.bloomingdales.com/shop/product/canali-siena-melange-textured-solid-regular-fit-sport-coat?ID=5124971&CategoryID=1065659',
  'https://www.shopsimon.com/products/jole-x5-crystal-embellished-heels-3',
  'https://www.shopsimon.com/products/mens-leather-derby-shoes-in-black-1',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-abstract-butterfly-silk-chiffon-kaftan-prod192590279',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-techno-canvas-jacket-prod192250100',
  'https://www.bergdorfgoodman.com/p/kiton-mens-abstract-medallion-silk-tie-prod193870011',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-kent-hand-tailored-plaid-sport-coat-prod196680103',
  'https://www.neimanmarcus.com/p/gucci-gg-plastic-cat-eye-sunglasses-prod286900026',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-garment-dyed-fin-prod287450082',
  'https://www.bergdorfgoodman.com/p/kiton-mens-multi-floral-silk-tie-prod193860091',
  'https://www.shopsimon.com/products/ferragamo-womens-gancino-28mm-quartz-watch-1',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-embroidered-logo-wool-cashmere-baseball-cap-prod281640173',
  'https://www.shopsimon.com/products/leather-logo-belt-2',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cashmere-turtleneck-sweater-prod285470132',
  'https://www.shopsimon.com/products/womens-gancini-chelsea-boots-in-red',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-cable-sequined-mesh-bodysuit-prod284850053',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-diagonal-wool-tweed-midi-sartorial-pencil-skirt-prod193920183',
  'https://www.bergdorfgoodman.com/p/kiton-mens-silk-and-cotton-short-sleeve-overshirt-prod198320236',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-ruffled-hem-cotton-silk-skirt-prod282920526',
  'https://www.shopsimon.com/products/mens-driver-with-gancini-ornament-loafer-in-brown',
  'https://www.neimanmarcus.com/p/etro-paisley-print-long-sleeve-belted-maxi-shirtdress-prod282180107',
  'https://www.bergdorfgoodman.com/p/kiton-mens-large-check-sport-shirt-prod198320237',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-round-textured-stud-earrings-prod286740340',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-water-resistant-prod287440205',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-monili-loop-shearling-lined-suede-combat-boots-prod193990105',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-cable-sequined-mesh-bodysuit-prod284860033',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-tonal-prince-of-wales-patch-pocket-sport-coat-prod194080051',
  'https://www.shopsimon.com/products/sal-85-ankle-booties',
  'https://www.shopsimon.com/products/lace-up-open-knit-sweater-in-cream',
  'https://www.bergdorfgoodman.com/p/kiton-silk-long-sleeve-shirt-prod193900274',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-twisted-knot-cuff-prod283220157',
  'https://www.bloomingdales.com/shop/product/etro-silk-printed-scarf-neck-blouse?ID=5694550&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-mid-rise-slim-leg-ankle-pants-prod193300139',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-long-sleeve-polo-sweater-prod194790453',
  'https://www.bergdorfgoodman.com/p/etro-button-front-denim-paisley-midi-dress-prod194070117',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-suede-full-zip-bomber-jacket-prod198321321',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-boucle-jersey-tweed-tailored-midi-skirt?ID=5652448&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/dolce-gabbana-mens-strobel-portofino-low-top-sneakers?ID=5312742&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-metallic-cashmere-silk-mock-neck-top-prod285280338',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-tailored-herringbone-sport-coat-prod282310343',
  'https://www.shopsimon.com/products/cumulus-draped-sleeve-maxi-dress-in-white',
  // 'https://www.ssense.com/en-us/men/product/bottega-veneta/black-bv1363s-sunglasses/17683881',
  'https://www.shopsimon.com/products/azha-x5-wrap-tie-heels-1',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-birdseye-suede-trim-quarter-zip-sweater-prod196680008',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-denim-monili-slingback-ballerina-flats-prod281850050',
  'https://www.shopsimon.com/products/ferragamo-womens-56-mm-grey-sunglasses-1',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-embellished-column-gown?ID=5565206&CategoryID=1065659',
  'https://www.shopsimon.com/products/jessie-crystal-embellished-slingback-pumps-1',
  'https://www.shopsimon.com/products/212-vip-rose-elixir-5-ml-eau-de-parfum-elixir-mini-for-women',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-cherry-blossom-bubble-twist-trim-cardigan?ID=5534772&CategoryID=1065659',
  'https://www.shopsimon.com/products/carolina-herrera-silk-palazzo-pant-1',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cotton-classic-fit-micro-square-sport-shirt-prod285470033',
  'https://www.shopsimon.com/products/plaid-print-sleeveless-shirt',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-plaid-short-sleeve-sweater-prod284860056',
  'https://www.shopsimon.com/products/womens-ella-mules-in-red',
  'https://www.bergdorfgoodman.com/p/kiton-mens-medallion-silk-7-fold-tie-prod193870014',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-petal-drop-crystal-earrings-prod286730978',
  'https://www.neimanmarcus.com/p/carolina-herrera-embellished-mock-neck-crop-top-prod284930024',
  'https://www.bloomingdales.com/shop/product/gucci-guccissima-oval-sunglasses-51mm?ID=5372990&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-paillette-cashmere-mohair-zip-cardigan-prod193920012',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-tiered-ruffled-sleeve-blouse?ID=5520129&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-ripley-wool-cashmere-four-pocket-jacket-prod194800122',
  'https://www.shopsimon.com/products/carolina-herrera-cashmere-cape-sweater',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-double-pleated-corduroy-trousers-prod285440624',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-embellished-long-sleeve-midi-dress-prod196640120',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-cotton-slim-leg-ankle-pull-on-pants-prod194270092',
  'https://www.shopsimon.com/products/carolina-herrera-womens-nude-55mm-sunglasses',
  'https://www.shopsimon.com/products/carolina-herrera-button-midi-dress',
  'https://www.neimanmarcus.com/p/carolina-herrera-3d-floral-embellished-long-sleeve-midi-dress-prod284810226',
  'https://www.bloomingdales.com/shop/product/canali-microtextured-regular-fit-dress-shirt?ID=5366700&CategoryID=1065659',
  'https://www.shopsimon.com/products/mens-cube-gancini-print-lace-up-sneakers-in-red',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-brushed-cashmere-twill-blazer-prod285600690',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-floral-embellished-wool-shift-dress-prod196640015',
  'https://www.shopsimon.com/products/salvatore-ferragamo-leather-womens-handbag-1',
  'https://www.shopsimon.com/products/carolina-herrera-wool-blend-single-breasted-coat',
  'https://www.shopsimon.com/products/emii-85-mules',
  'https://www.bloomingdales.com/shop/product/gucci-generation-guccissima-rectangular-sunglasses-54mm?ID=5371208&CategoryID=1065659',
  'https://www.shopsimon.com/products/deconstructed-jean-in-vapour',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-hand-tailored-tick-weave-stables-jacket-prod285470293',
  'https://www.bloomingdales.com/shop/product/dolce-gabbana-square-sunglasses-54mm?ID=5102056&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-ruffle-off-the-shoulder-top-prod193290071',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-standard-fit-honeycomb-mesh-polo-shirt-prod287120564',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-wool-cashmere-knit-midi-pencil-skirt-prod193420025',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-crystal-fringe-earrings-prod193940014',
  'https://www.bergdorfgoodman.com/p/etro-mid-rise-jeans-prod197490135',
  'https://www.bergdorfgoodman.com/p/kiton-mens-linen-coral-print-short-sleeve-shirt-prod198320320',
  'https://www.bloomingdales.com/shop/product/dolce-gabbana-square-sunglasses-54mm?ID=4753976&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-plexy-and-raffia-flowers-earrings-prod198500060',
  'https://www.shopsimon.com/products/sandra-suede-platform-booties',
  'https://www.shopsimon.com/products/giunone-leather-slides',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cashmere-glen-plaid-overshirt-prod285600668',
  'https://www.shopsimon.com/products/farrah-pumps',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-floral-full-midi-skirt-prod193300151',
  'https://www.bloomingdales.com/shop/product/etro-printed-shirt?ID=5570303&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-thigh-patch-wide-leg-cargo-pants-prod282260125',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-organza-hem-knit-hooded-sweater-prod197840085',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-velvet-peak-lapel-single-breasted-sport-coat-prod285470373',
  // 'https://www.ssense.com/en-us/men/product/bottega-veneta/black-dizzy-square-sunglasses/17684281',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-sleeveless-cherry-blossom-cady-dress?ID=5534796&CategoryID=1065659',
  'https://www.shopsimon.com/products/wool-melton-peacoat-in-ink',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-modern-fit-corduroy-button-down-shirt-prod281660496',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-brushed-cashmere-twill-slim-blazer-prod196690019',
  'https://www.shopsimon.com/products/womens-gardena-sock-ankle-sneakers-in-black',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-waist-tab-straight-fit-cotton-corduroy-pants-prod196690003',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-butterfly-print-cardigan?ID=5534762&CategoryID=1065659',
  'https://www.ssense.com/en-us/men/product/bottega-veneta/black-keyhole-sunglasses/17684211',
  'https://www.shopsimon.com/products/janna-ankle-boots',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-crystal-wave-drop-earrings-prod286880520',
  'https://www.bergdorfgoodman.com/p/kiton-mens-mini-houndstooth-wool-cashmere-pants-prod198330323',
  'https://www.shopsimon.com/products/ferragamo-womens-sf943s-60mm-sunglasses-5',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-polo-shirt-prod198320978',
  'https://www.shopsimon.com/products/oscar-de-la-renta-checkered-guipure-fringe-silk-blend-tank',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-wool-cashmere-tonal-chevron-sport-coat-prod285440625',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-the-eastham-quilted-jacket-prod285630049',
  'https://www.shopsimon.com/products/mens-driver-gancini-crochet-loafer-in-black',
  'https://www.shopsimon.com/products/dennis-crochet-sneakers',
  'https://www.shopsimon.com/products/v-neck-oversized-maxi-dress',
  'https://www.shopsimon.com/products/oscar-de-la-renta-silk-lined-blouse-1',
  'https://www.shopsimon.com/products/oscar-de-la-renta-silk-lined-pant-1',
  'https://www.bergdorfgoodman.com/p/kiton-mens-small-paisley-silk-7-fold-tie-prod193870002',
  'https://www.shopsimon.com/products/tom-ford-mens-52mm-shiny-black-opticals-ft5930-d-b-052-52',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-knit-monili-cap-toe-sneakers-prod286730331',
  'https://www.bloomingdales.com/shop/product/etro-printed-tie-neck-midi-dress?ID=5694546&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/carolina-herrera-3d-floral-embellished-strapless-column-gown-prod284850065',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-wave-print-sport-shirt-prod198330136',
  'https://www.bergdorfgoodman.com/p/kiton-mens-medallion-woven-silk-7-fold-tie-prod193860180',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-cable-half-placket-sweater-prod196680119',
  'https://www.bergdorfgoodman.com/p/kiton-mens-slim-stretch-flat-front-pants-prod198330169',
  'https://www.shopsimon.com/products/era-patent-leather-mules',
  'https://www.shopsimon.com/products/mens-driver-gancini-loafers-in-nebbiolo',
  // 'https://www.ssense.com/en-us/men/product/gucci/gold-rectangular-sunglasses/17805731',
  'https://www.shopsimon.com/products/zigzag-print-scarf-1',
  'https://www.bloomingdales.com/shop/product/tom-ford-metal-accent-square-sunglasses-54mm?ID=4932571&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-wool-cashmere-sn-prod287440223',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-carleton-quilted-suede-vest-prod285610026',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-belted-wool-alpaca-check-blazer-prod193920010',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cashmere-blend-crewneck-sweater-prod198321000',
  'https://www.shopsimon.com/products/detroit-1-low-top-sneakers',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cashmere-slim-fit-turtleneck-sweater-prod285470313',
  'https://www.bergdorfgoodman.com/p/brioni-mens-cotton-petite-grid-check-dress-shirt-prod198820244',
  'https://www.shopsimon.com/products/salvatore-ferragamo-leather-womens-handbag-4',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-exclusive-ribbed-cashmere-mock-neck-sweater-prod197270044',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-cherry-blossom-5-drop-earrings-prod192640071',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-stripe-button-down-linen-shirt-with-piping-collar-prod286790246',
  'https://www.bergdorfgoodman.com/p/brioni-mens-tricot-silk-knit-tie-prod198820486',
  'https://www.neimanmarcus.com/p/etro-paisley-scarf-blouse-prod285230209',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cotton-melange-herringbone-dress-shirt-prod285600576',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-short-sleeve-cutout-hem-tweed-dress?ID=5534751&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/etro-printed-wide-leg-belted-jeans?ID=5570318&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/canali-kei-windowpane-unstructured-trim-fit-sport-coat?ID=5442097&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/kiton-mens-small-paisley-silk-7-fold-tie-prod193860095',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-plaid-twill-paneled-shirtdress-prod282920469',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-floral-silk-long-sleeve-trench-gown-prod193280012',
  'https://www.shopsimon.com/products/mens-cassina-quilted-leather-low-top-sneakers-in-brown',
  'https://www.bloomingdales.com/shop/product/canali-siena-melange-textured-solid-regular-fit-sport-coat?ID=3776306&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-ponte-turtleneck-maxi-dress-prod282920709',
  'https://www.shopsimon.com/products/white-hooded-mini-dress',
  'https://www.neimanmarcus.com/p/carolina-herrera-turtleneck-paillette-rose-wool-cashmere-sweater-prod284850007',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-cherry-blossom-degrade-jacquard-coat?ID=5534784&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/gucci-logo-acetate-cat-eye-sunglasses-prod198500021',
  'https://www.shopsimon.com/products/womens-ninette-sock-sneakers-in-medium-blue',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-velvet-maxi-trumpet-skirt-prod196640329',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-sparkly-zip-jacket-prod282310098',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-pleated-mesh-monili-clutch-bag-prod190720432',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-monili-collar-chambray-button-down-shirt-prod198320556',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-floral-silk-belted-long-sleeve-trench-gown-prod196640338',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-double-face-stretch-wool-pants-prod192600082',
  'https://www.shopsimon.com/products/selestina-fur-mules',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-puff-sleeve-cocktail-dress?ID=5399070&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-and-silk-snap-front-overshirt-prod198320265',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-kent-hand-tailored-velvet-jacket-prod285470384',
  'https://www.shopsimon.com/products/womens-mirrored-heel-ankle-boots-in-black-brown',
  'https://www.bergdorfgoodman.com/p/gucci-beveled-acetate-round-sunglasses-prod195120030',
  'https://www.bergdorfgoodman.com/p/kiton-mens-chambray-modern-fit-button-down-shirt-prod194100003',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-classic-fit-micro-houndstooth-twill-button-down-shirt-prod285620100',
];


export const BEST_DEALS_LINKS_SET = [
  'https://www.shopsimon.com/products/oscar-de-la-renta-blouse-5',
  'https://www.shopsimon.com/products/womens-gancini-motif-sneakers-in-beige',
  'https://www.bloomingdales.com/shop/product/tom-ford-butterfly-sunglasses-55mm?ID=5685286&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mat-leather-equestrian-riding-boots-prod193990110',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-pave-crystal-wrap-ring-prod192640063',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-wide-stripe-linen-two-piece-suit-prod277620091',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-dbl-merc-ctn-piq-prod287440267',
  'https://www.shopsimon.com/products/oscar-de-la-renta-crepe-silk-lined-wool-blend-shift-dress-3',
  'https://www.shopsimon.com/products/eva-x5-croc-embossed-pumps',
  'https://www.shopsimon.com/products/mens-vara-bit-driver-moccasins-in-black',
  'https://www.neimanmarcus.com/p/stefano-ricci-micro-neat-stripe-prod287450154',
  'https://www.shopsimon.com/products/oscar-de-la-renta-romper',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-plexy-and-raffia-flowers-earrings-prod286880599',
  'https://www.shopsimon.com/products/womens-buckle-detail-ballerina-pumps-in-black',
  'https://www.shopsimon.com/products/carolina-herrera-slip-dress',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-twisted-knot-stud-earrings-prod192640057',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cotton-velvet-bow-tie-prod285480047',
  'https://www.bergdorfgoodman.com/p/etro-ruffled-long-sleeve-mini-dress-prod194080031',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-glam-check-sequined-pleated-crop-trousers-prod193920020',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-butterfly-print-wool-crewneck-sweater-prod192600094',
  'https://www.bloomingdales.com/shop/product/tom-ford-wyatt-cat-eye-sunglasses-56mm?ID=3970882&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mohair-open-work-crewneck-sweater-prod198320140',
  'https://www.shopsimon.com/products/otello-leather-booties',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-pleated-self-tie-full-midi-dress-prod193510091',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-lace-embroidered-split-neck-dress?ID=5294266&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mellow-mini-ruched-leather-bucket-bag-prod193480003',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-painted-stripe-sport-shirt-prod198320285',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-stirrup-buckle-leather-belt-prod194960132',
  'https://www.shopsimon.com/products/womens-small-camera-case-logo-crossbody-bag-in-pink',
  'https://www.shopsimon.com/products/shaula-crochet-sandals',
  'https://www.shopsimon.com/products/womens-gancini-sneakers-in-white',
  'https://www.bloomingdales.com/shop/product/tom-ford-square-sunglasses-55mm?ID=5685283&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-basketweave-linen-sport-shirt-prod284970070',
  'https://www.shopsimon.com/products/giasone-ankle-boots',
  'https://www.shopsimon.com/products/double-breasted-cropped-jacket-in-brown',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-ruched-dress?ID=5565318&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-bouquet-print-button-down-icon-blouse-prod193300192',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-wool-flannel-wide-leg-ankle-cargo-pants-prod193920181',
  'https://www.neimanmarcus.com/p/etro-mid-rise-jeans-prod286880669',
  'https://www.shopsimon.com/products/etro-wool-blend-shift-dress',
  'https://www.shopsimon.com/products/elina-x5-gancini-logo-heels-2',
  'https://www.shopsimon.com/products/vara-bow-smooth-leather-shoulder-bag',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-oversized-cashmere-net-stitch-sweater-prod193920173',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-ruched-v-neck-column-dress-prod193310106',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-stretch-corduroy-pants-prod285620043',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-sleeveless-knee-length-floral-print-dress?ID=5520122&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/etro-long-cape-dress?ID=5570300&CategoryID=1065659',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-womens-handbag',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-sequined-mohair-wool-open-knit-crewneck-sweater-prod282310029',
  'https://www.bergdorfgoodman.com/p/kiton-mens-baby-blue-straight-leg-jeans-prod198320711',
  'https://www.shopsimon.com/products/polo-ralph-lauren-sleep-shirt-mens-blue-terry-short-sleeve-pullover-asm256',
  'https://www.bergdorfgoodman.com/p/kiton-mens-contrast-stitch-polo-shirt-prod198330072',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sequined-silk-organza-bomber-jacket-prod193930042',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cotton-and-cashmere-maxi-paisley-silk-tie-prod196680013',
  'https://www.shopsimon.com/products/wrapped-denim-column-skirt-in-ink',
  'https://www.shopsimon.com/products/eva-x5-metallic-leather-pumps',
  'https://www.shopsimon.com/products/oscar-de-la-renta-mini-dress-1',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-embellished-round-neck-dress?ID=5634792&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-textured-wool-notch-lapel-sport-coat-prod194790326',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-rhinestone-drop-earrings-prod283220202',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-fireworks-tassel-earrings-prod286730980',
  'https://www.bloomingdales.com/shop/product/etro-silk-printed-maxi-shirtdress?ID=5700086&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/carolina-herrera-embellished-tweed-mock-neck-mini-dress-prod284850051',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-a-line-double-cashmere-midi-skirt-prod192240018',
  'https://www.neimanmarcus.com/p/carolina-herrera-crystal-button-front-tweed-midi-dress-with-belt-prod284810191',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-kent-paisley-silk-sport-coat-prod198450560',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-sleeveless-scoop-neck-midi-dress-with-sash?ID=5520102&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-donegal-effect-c-prod287440321',
  'https://www.shopsimon.com/products/carolina-herrera-mock-neck-top',
  'https://www.shopsimon.com/products/velvet-straight-leg-pants',
  'https://www.shopsimon.com/products/womens-wanda-bi-fold-wallet-in-beige',
  'https://www.shopsimon.com/products/womens-willis-70mm-pumps-in-beige-khaki',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-v-neck-cashmere-cardigan-prod281640108',
  'https://www.bergdorfgoodman.com/p/kiton-mens-linen-coral-print-full-zip-bomber-jacket-prod198320970',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-textured-scramble-double-drop-earrings-prod192680132',
  'https://www.shopsimon.com/products/chino-pants-1',
  'https://www.shopsimon.com/products/mens-embossed-logo-leather-bifold-wallet-in-lapis',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-slim-light-wash-denim-jeans-prod281640294',
  'https://www.neimanmarcus.com/p/carolina-herrera-diane-pinstripe-wool-wide-leg-pants-prod284860007',
  'https://www.bergdorfgoodman.com/p/kiton-mens-stretch-waistband-flat-front-trousers-prod198330238',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-cashmere-wool-flannel-wide-sartorial-pants-with-belt-prod193920054',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-watercolor-orchid-embellished-pants?ID=5294249&CategoryID=1065659',
  'https://www.shopsimon.com/products/sonya-leather-platform-sandals-1',
  'https://www.bloomingdales.com/shop/product/dolce-gabbana-womens-knotted-espadrille-sandals?ID=5290731&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/etro-long-sleeve-velvet-paisley-dress-prod194080032',
  'https://www.shopsimon.com/products/womens-logo-embossed-low-top-sneakers-in-pink',
  'https://www.bloomingdales.com/shop/product/tom-ford-browline-round-sunglasses-53mm?ID=5738154&CategoryID=1065659',
  'https://www.shopsimon.com/products/wide-leg-allover-mini-geo-silk-twill-pants-in-black-blue',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-tailored-wide-leg-pants-prod193300156',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-crystal-wave-necklace-prod193940050',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-tweed-embroidered-cutout-midi-suiting-skirt-prod280190043',
  'https://www.shopsimon.com/products/tom-ford-womens-52mm-dark-brown-sunglasses-ft1191-53e-52',
  'https://www.shopsimon.com/products/mens-leather-sneakers-in-blue',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-sequined-lace-pants-prod284930064',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-hybrid-full-zip-knit-sweater-vest-prod285620126',
  'https://www.shopsimon.com/products/womens-palladium-scarf-ring-in-silver',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-short-sleeve-silk-blend-polo-shirt-prod193420050',
  'https://www.bloomingdales.com/shop/product/etro-printed-silk-shirt?ID=5570302&CategoryID=1065659',
  'https://www.shopsimon.com/products/pleated-wrap-maxi-skirt',
  'https://www.shopsimon.com/products/womens-biker-leather-jacket-in-white',
  'https://www.shopsimon.com/products/mens-deconstructed-loafer-with-gancini-ornament-in-midnight-blue',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-tweed-shift-dress?ID=5399052&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/tom-ford-saltzman-butterfly-sunglasses-53mm?ID=5738156&CategoryID=1065659',
  'https://www.shopsimon.com/products/salvatore-ferragamo-leather-womens-handbag-3',
  'https://www.shopsimon.com/products/vega-new-diamond-watch-2',
  'https://www.shopsimon.com/products/nima-metallic-knit-sneakers',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-pom-pom-flower-stud-earrings-prod286730296',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-one-shoulder-column-gown?ID=5565205&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-modern-fit-corduroy-button-down-shirt-prod198321243',
  'https://www.bloomingdales.com/shop/product/tom-ford-philippe-square-sunglasses-58mm?ID=5685288&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/kiton-short-sleeve-buttoned-dress-prod193900270',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mohair-cozy-candy-floss-knit-crewneck-sweater-prod193920045',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-water-resistant-gabardine-jacket-prod282320086',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-long-sleeve-asymmetrical-hem-cherry-blossom-poplin-dress?ID=5534774&CategoryID=1065659',
  'https://www.shopsimon.com/products/gancini-bracelet-watch-14',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-wool-and-nylon-fair-isle-knit-cardigan-prod281640389',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cashmere-half-zip-sweater-prod285470396',
  'https://www.shopsimon.com/products/vidette-patent-leather-wedge-sandals-2',
  'https://www.shopsimon.com/products/shay-10-caged-slingback-sandals',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sparkling-wool-blend-padded-jacket-with-removable-shearling-collar-prod193920106',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-sleeveless-cherry-guipure-cocktail-dress?ID=5534756&CategoryID=1065659',
  'https://www.shopsimon.com/products/double-knit-hoodie-in-khaki',
  'https://www.bloomingdales.com/shop/product/dolce-gabbana-womens-beachwear-sandals?ID=5545432&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-sleeveless-butterfly-jacquard-knit-dress?ID=5534761&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/canali-siena-hopsack-plaid-regular-fit-sport-coat?ID=5366693&CategoryID=1065659',
  'https://www.shopsimon.com/products/carolina-herrera-wool-blend-midi-dress-1',
  'https://www.shopsimon.com/products/womens-patent-leather-pumps-in-beige',
  'https://www.shopsimon.com/products/carolina-herrera-embellished-crewneck-midi-dress-1',
  'https://www.bloomingdales.com/shop/product/canali-long-sleeve-button-front-shirt?ID=5684690&CategoryID=1065659',
  'https://www.shopsimon.com/products/opaline-sequin-strapless-gown-in-glisten-clear',
  'https://www.neimanmarcus.com/p/stefano-ricci-denim-prod287440207',
  'https://www.shopsimon.com/products/cassina-slip-on-sneakers',
  'https://www.bergdorfgoodman.com/p/kiton-mens-small-paisley-silk-7-fold-tie-prod193870028',
  'https://www.shopsimon.com/products/sal-85-ankle-booties-1',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-leisure-pant-wit-prod287440020',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-jacquard-fringe-shift-dress-prod192250016',
  'https://www.shopsimon.com/products/long-sleeve-wrap-detailed-abstract-ombre-poplin-dress-in-canyon-navy',
  'https://www.bloomingdales.com/shop/product/etro-printed-long-sleeve-jersey-top?ID=5700088&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/kiton-mens-silk-and-cotton-button-front-overshirt-prod198320282',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-shiny-detail-shearling-lined-suede-mules-prod193990108',
  'https://www.shopsimon.com/products/mens-leather-boat-shoes-in-purple',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-woven-oxford-spread-collar-sport-shirt-prod195800088',
  'https://www.neimanmarcus.com/p/carolina-herrera-draped-off-shoulder-gown-prod284920057',
  'https://www.shopsimon.com/products/womens-ruched-long-sleeve-mini-dress-in-black',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sequined-english-rib-sweater-prod192250092',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-satin-tie-front-wrap-shirtdress-prod282920434',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-check-sport-shirt-prod198320189',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-cap-sleeve-twist-neck-draped-cocktail-dress?ID=5534755&CategoryID=1065659',
  'https://www.shopsimon.com/products/mens-leather-gloves-in-black',
  'https://www.shopsimon.com/products/vilenica-veiled-off-the-shoulder-top-in-black',
  'https://www.shopsimon.com/products/womens-wool-belted-wrap-solid-coat-in-camel',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-emerald-crystal-scramble-necklace-prod193940181',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-shoulder-womens-bag-1',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-fair-isle-intarsia-crewneck-sweater-prod196690022',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-cotton-rib-polo-prod287440015',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-leather-curved-heel-pumps-prod193990126',
  'https://www.shopsimon.com/products/mens-gancini-suede-driving-shoes-in-brown',
  'https://www.shopsimon.com/products/salvatore-ferragamo-calfskin-lace-up-mens-boots',
  'https://www.shopsimon.com/products/mini-vara-bow-crossbody-bag-1',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-denim-pointed-toe-slingback-pumps-with-monili-trim-prod192080188',
  'https://www.neimanmarcus.com/p/carolina-herrera-intarsia-knit-floral-flare-skirt-prod284890174',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-cashmere-wool-flannel-double-breasted-blazer-prod193920120',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-beaded-crystal-heart-earrings-prod193940017',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-crystal-wave-ring-prod198490018',
  'https://www.shopsimon.com/products/womens-panelled-design-leather-tote-bag-in-black',
  'https://www.shopsimon.com/products/ninette-high-top-sock-sneakers-1',
  'https://www.shopsimon.com/products/pointelle-cami-sleep-dress-in-egret',
  'https://www.shopsimon.com/products/charm-medallion-silk-twill-paisley-blouse-in-pink-multi',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-cherry-blossom-tweed-embroidered-mini-dress-prod192590306',
  'https://www.shopsimon.com/products/womens-high-waisted-tailored-shorts-in-brown',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-suede-carved-leather-belt-prod197560007',
  'https://www.shopsimon.com/products/tom-ford-womens-67mm-rose-gold-sunglasses-ft1185-28e-67',
  'https://www.shopsimon.com/products/womens-flared-trouser-pants-in-black',
  'https://www.bergdorfgoodman.com/p/etro-short-sleeve-knit-paisley-sweater-prod194070114',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-sparkling-cotton-mini-dress-prod282310032',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-crystal-button-front-tweed-midi-dress-with-belt-prod196640370',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-striped-neck-tie-prod197320057',
  'https://www.bloomingdales.com/shop/product/etro-silk-cold-shoulder-top?ID=5486418&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-bow-embellished-midi-skirt-prod193290055',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-wool-silk-and-cashmere-full-zip-sweater-prod196890055',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-flannel-wool-monili-heel-pumps-prod286670495',
  'https://www.shopsimon.com/products/ilary-pointed-toe-pumps-1',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-silk-ruffled-mini-dress?ID=5520146&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-crystal-climber-earrings-prod193940127',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-cable-knit-cashmere-quarter-zip-sweater-prod285620459',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-excl-cashmere-h-prod287450138',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-gregory-cashmere-check-sport-coat-prod194800235',
  'https://www.shopsimon.com/products/ferragamo-1927-chrono-leather-watch-1',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-striped-paillette-crispy-silk-chiffon-button-down-blouse-prod198330066',
  'https://www.bloomingdales.com/shop/product/etro-printed-silk-trousers?ID=5570292&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/etro-v-neck-paisley-stampa-silk-sweater-prod285280092',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-tweed-embroidered-cutout-skirt?ID=5534749&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/kiton-mens-plaid-wool-and-silk-casual-overshirt-prod198320690',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-8-wale-corduroy-three-button-blazer-prod285620055',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-wool-and-nylon-melange-polo-sweater-prod198320652',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-satin-peak-lapel-velvet-dinner-jacket-prod281640198',
  'https://www.shopsimon.com/products/deva-sandals-2',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-suede-monili-strap-slip-on-loafers-prod286660355',
  'https://www.shopsimon.com/products/womens-ankle-chain-link-ballet-flats-in-black',
  'https://www.bloomingdales.com/shop/product/canali-siena-screenweave-regular-fit-suit?ID=5442099&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-ribbed-knit-cash-prod287450070',
  'https://www.shopsimon.com/products/womens-dana-ankle-chain-pumps-in-black',
  'https://www.shopsimon.com/products/tom-ford-womens-5605c-56mm-sunglasses',
  'https://www.shopsimon.com/products/ninette-high-top-sock-sneakers-3',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-sueded-cotton-poplin-button-down-shirt-prod194790338',
  'https://www.shopsimon.com/products/mens-gancini-low-top-sneakers-in-rhinoceros-grey',
  'https://www.shopsimon.com/products/womens-lober-ankle-boots-in-bone',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-exclusive-satin-prod197320094',
  'https://www.shopsimon.com/products/cosma-sock-high-top-sneakers-1',
  'https://www.shopsimon.com/products/jersey-sleep-shirt-in-white-cloud',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-cable-knit-half-placket-mock-neck-sweater-prod196680072',
  'https://www.neimanmarcus.com/p/carolina-herrera-tulip-embellished-wool-silk-sweater-prod284850005',
  'https://www.shopsimon.com/products/sal-85-glitter-ankle-booties',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-silk-off-the-shoulder-column-dress?ID=5565204&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brioni-mens-cotton-graph-check-dress-shirt-prod194060005',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-turtleneck-sweater?ID=5634795&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-wes-textured-suede-belt-with-monili-trim-prod197550051',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-silk-organza-all-over-pailet-prod193920276',
  'https://www.neimanmarcus.com/p/brioni-mens-textured-silk-tie-prod287230434',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-harrison-linen-thin-stripe-sport-shirt-prod194800294',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-the-eastham-quilted-vest-prod285620339',
  'https://www.bloomingdales.com/shop/product/etro-printed-shirt?ID=5486415&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-80mm-monili-suede-espadrille-wedge-sandals-prod197860052',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-cashmere-turtlen-prod287440292',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-tattersall-check-modern-fit-sport-shirt-prod196810929',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-midi-sleeve-tweed-jacket?ID=5651885&CategoryID=1065659',
  'https://www.shopsimon.com/products/mens-parigi-19-loafers-in-grey-black',
  'https://www.shopsimon.com/products/altaire-strappy-mules',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-cashmere-v-neck-sweater-prod265170254',
  'https://www.shopsimon.com/products/ferragamo-zea-leather-flat',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-silk-embellished-mini-dress?ID=5565233&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-long-sleeve-merc-prod287440048',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-crystal-wave-drop-earrings-prod286730996',
  'https://www.shopsimon.com/products/leather-chelsea-boots-1',
  'https://www.neimanmarcus.com/p/stefano-ricci-squares-prod287440349',
  'https://www.bergdorfgoodman.com/p/etro-mid-rise-jeans-prod198510107',
  'https://www.shopsimon.com/products/canaria-suede-booties-1',
  'https://www.bergdorfgoodman.com/p/brioni-mens-textured-silk-tie-prod198490095',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-suede-button-fro-prod287440096',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-peony-unraveled-jacquard-sleeveless-mini-day-dress-prod194420067',
  'https://www.shopsimon.com/products/polo-bear-cotton-long-sleeve-pajama-set-in-bear-red',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-cherry-blossom-dangle-earrings-prod192640046',
  'https://www.bloomingdales.com/shop/product/canali-siena-sharkskin-regular-fit-suit?ID=5124976&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-techno-cotton-button-front-top-with-brass-trim-prod193920223',
  'https://www.shopsimon.com/products/mens-tote-bag-with-signature-in-beige-khaki',
  'https://www.shopsimon.com/products/sonya-suede-platform-sandals',
  'https://www.shopsimon.com/products/etro-print-t-shirt',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-suede-monili-tab-runner-sneakers-prod192080208',
  'https://www.neimanmarcus.com/p/etro-straight-leg-cotton-denim-jeans-prod282180086',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-sleeveless-cherry-guipure-embroidered-high-low-dress-with-belt-prod192590367',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-piece-dyed-cotton-western-shirt-prod198321357',
  'https://www.shopsimon.com/products/madison-pajama-set-in-bear-red-1',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-mock-neck-sleeveless-top?ID=5565399&CategoryID=1065659',
  'https://www.shopsimon.com/products/carolina-herrera-wool-blend-midi-dress',
  'https://www.shopsimon.com/products/carolina-herrera-wool-blend-collarless-jacket',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-floral-wide-leg-pants-prod193310084',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-stretch-silk-satin-track-trousers-prod193920101',
  'https://www.shopsimon.com/products/cable-knit-wool-cashmere-sweater-in-black',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-sleeveless-butterfly-jacquard-knit-midi-dress-prod192600073',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-corded-botanical-guipure-tailored-skirt-prod282890052',
  'https://www.shopsimon.com/products/carolina-herrera-womens-55mm-teal-brown-opticals',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-gingham-check-lo-prod287450095',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-brocade-dress?ID=5565462&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-embellished-silk-dress?ID=5634799&CategoryID=1065659',
  'https://www.shopsimon.com/products/mens-alta-lace-up-sneakers-in-grey',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-shearling-lined-button-front-parka-prod194070160',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-crystal-wave-ring-prod286730992',
  'https://www.shopsimon.com/products/carolina-herrera-silk-pearl-button-top',
  'https://www.shopsimon.com/products/mens-gancini-palinuro-driving-shoes-in-blue',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-orchids-cropped-top?ID=5294445&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-calfskin-leather-loafer-mules-prod192080195',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cotton-plaid-double-pocket-button-down-shirt-prod196690101',
  'https://www.shopsimon.com/products/womens-engraved-star-ring-in-silver',
  'https://www.shopsimon.com/products/euripilo-leather-loafers-1',
  'https://www.neimanmarcus.com/p/carolina-herrera-tulip-mock-neck-midi-dress-prod284930003',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-stripe-dress-shirt-prod198320758',
  'https://www.bergdorfgoodman.com/p/brioni-mens-micro-paisley-jacquard-silk-tie-prod198820482',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cashmere-birdseye-polo-sweater-prod285610027',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-suede-boat-shoe-prod198370068',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-half-zip-sweater-prod194790253',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-cotton-corduroy-wide-leg-pants-prod282930206',
  'https://www.shopsimon.com/products/carolina-herrera-womens-55mm-havana-red-sunglasses',
  'https://www.shopsimon.com/products/leather-combat-boots-2',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-embroidered-flower-off-the-shoulder-top-prod193230041',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-cotton-flat-knit-henley-shirt-prod197260088',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-linen-and-mulberry-silk-glen-plaid-tie-prod194790439',
  // 'https://www.ssense.com/en-us/men/product/bottega-veneta/silver-aviator-glasses/17778741',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-embellished-mini-dress?ID=5565459&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/gucci-mens-gg1426sm-gg-acetate-rectangle-sunglasses-prod191550004',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-rectangle-crystal-bracelet-prod193940079',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-suede-monili-strap-slip-on-loafers-prod192080177',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-glen-plaid-overshirt-prod196690153',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-multi-stripe-dress-shirt-prod198320602',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-embellished-shift-dress?ID=5634798&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-botanical-guipure-short-sleeve-mini-dress-prod194420093',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-mini-geometric-silk-tie-prod194790362',
  'https://www.shopsimon.com/products/womens-classic-denim-jacket-in-blue',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-leather-ankle-booties-with-monili-pull-tab-prod193990109',
  'https://www.shopsimon.com/products/carolina-herrera-v-neck-fan-bodice-silk-column-gown',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-sequin-tweed-suit-pencil-skirt?ID=5534766&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-birdseye-quarter-zip-sweater-prod196690031',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-sparkling-wool-blend-padded-jacket-with-removable-shearling-collar-prod282320042',
  'https://www.bloomingdales.com/shop/product/canali-cotton-jersey-slim-fit-sport-shirt?ID=5536161&CategoryID=1065659',
  'https://www.shopsimon.com/products/womens-vivaldo-high-shine-ballerina-shoes-in-pink',
  'https://www.shopsimon.com/products/salvatore-ferragamo-leather-womens-handbag-2',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-degrade-check-spread-collar-dress-shirt-prod193870040',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sequined-net-stitch-cashmere-zip-cardigan-prod193920189',
  'https://www.shopsimon.com/products/jana-suede-booties',
  'https://www.neimanmarcus.com/p/carolina-herrera-virgin-wool-mini-skirt-prod284900005',
  'https://www.shopsimon.com/products/flared-cotton-chino-trousers',
  'https://www.shopsimon.com/products/nima-knit-sneakers',
  'https://www.shopsimon.com/products/womens-gancini-slip-on-mules-in-brown',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-satin-cady-a-line-dress-with-precious-monili-collar-prod193920244',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-twisted-knot-necklace-prod192640050',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cable-knit-cashmere-mockneck-sweater-prod285600723',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-mini-skirt?ID=5634847&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-donegal-wool-and-cashmere-notch-lapel-sport-coat-prod197330077',
  'https://www.shopsimon.com/products/womens-leather-ankle-boots-in-black-3',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-suede-comma-heel-knee-boots-prod192080210',
  'https://www.shopsimon.com/products/micro-stitch-knitted-top-in-black',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-strapless-rosette-dress?ID=5399120&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/kiton-abstract-drawstring-silk-pants-prod284890198',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-silk-paisley-neck-scarf-prod196690183',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-fine-wale-corduroy-two-piece-suit-prod195800054',
  'https://www.bloomingdales.com/shop/product/canali-siena-check-windowpane-regular-fit-sport-coat?ID=5442098&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/kiton-mens-corduroy-slim-single-pleated-pants-prod194430052',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-tiered-ruffle-sleeve-cotton-shirt-dress?ID=5520130&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-rectangular-crystal-chain-necklace-prod283220096',
  'https://www.neimanmarcus.com/p/oscar-de-la-renta-crystal-fringe-earrings-prod286730353',
  'https://www.bergdorfgoodman.com/p/kiton-mens-small-paisley-silk-tie-prod193860208',
  'https://www.shopsimon.com/products/long-sleeved-hooded-trench-coat',
  'https://www.shopsimon.com/products/carolina-herrera-embellished-off-shoulder-tiered-gown',
  'https://www.shopsimon.com/products/era-patent-leather-mules-5',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-cotton-viscose-satin-wide-leg-pants-prod284850066',
  'https://www.shopsimon.com/products/flor-55-sandals-1',
  'https://www.shopsimon.com/products/womens-high-waisted-wool-trouser-in-black',
  'https://www.shopsimon.com/products/oscar-de-la-renta-beaded-double-curtain-earrings-2',
  'https://www.shopsimon.com/products/womens-vara-bow-ballerina-shoes-in-black',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-blur-floral-button-down-icon-blouse-prod193300174',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-long-sleeve-peony-sweater?ID=5652421&CategoryID=1065659',
  'https://www.shopsimon.com/products/torris-knee-length-boots',
  'https://www.shopsimon.com/products/womens-pointed-toe-pumps-in-black-1',
  'https://www.shopsimon.com/products/womens-alan-mid-calf-boots-in-black',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-pleated-cherry-blossom-organza-gown?ID=5534798&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/polo-ralph-lauren-mens-classic-fit-check-poplin-sport-shirt-prod285620056',
  'https://www.shopsimon.com/products/carolina-herrera-womens-violet-havana-black-58mm-sunglasses',
  'https://www.shopsimon.com/products/v-neck-knit-sweater-1',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-solid-cotton-bow-tie-prod196680172',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-cashmere-chevron-vanise-quarter-zip-sweater-prod196720130',
  'https://www.shopsimon.com/products/ferragamo-mens-f-80-44mm-quartz-watch',
  'https://www.shopsimon.com/products/chino-pants',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-cotton-textured-polo-shirt-prod193350019',
  'https://www.bloomingdales.com/shop/product/dolce-gabbana-round-sunglasses-52mm?ID=4883779&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-double-breasted-corduroy-blazer-prod282310035',
  'https://www.bloomingdales.com/shop/product/etro-printed-long-sleeve-boat-neck-top?ID=5694551&CategoryID=1065659',
  'https://www.shopsimon.com/products/samanta-croc-embossed-platform-mules',
  'https://www.shopsimon.com/products/vara-bow-satin-pumps',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cotton-velvet-bow-tie-prod285480022',
  'https://www.bergdorfgoodman.com/p/kiton-mens-linen-drawstring-flat-front-shorts-prod198320286',
  'https://www.bergdorfgoodman.com/p/brioni-mens-cotton-multi-stripe-dress-shirt-prod194060006',
  'https://www.bergdorfgoodman.com/p/kiton-mens-cotton-stripe-dress-shirt-prod198320817',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-co-leisure-fit-w-prod287450089',
  'https://www.bloomingdales.com/shop/product/dolce-gabbana-rectangle-sunglasses-53mm?ID=5339019&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-hooded-zip-jacket-with-sheer-sequined-raindrop-sleeves-prod198320581',
  'https://www.bloomingdales.com/shop/product/canali-kei-melange-hopsack-unstructured-regular-fit-sport-coat?ID=5366694&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-pave-crystal-wrap-ring-prod192640067',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-suede-monili-slip-on-espadrilles-prod286660353',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-silk-floral-print-mini-dress?ID=5634842&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/etro-denim-dress?ID=5570321&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-glossed-skinny-leather-belt-prod285740534',
  'https://www.shopsimon.com/products/lunar-paneled-slip-on-sneakers-1',
];

export const LUXURY_CURATED_LINKS = [
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sparkly-zip-jacket-prod193920114',
  // 'https://www.neimanmarcus.com/p/brunello-cucinelli-cashmere-turtlen-prod287450130',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mat-leather-equestrian-riding-boots-prod193990110',
  // 'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cashmere-glen-plaid-overshirt-prod285600668',
  // 'https://www.bloomingdales.com/shop/product/canali-kei-wool-silk-donegal-quilted-lining-top-coat?ID=5543202&CategoryID=1065659',
  // 'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-superfine-nylon-snap-front-quilted-vest-prod196690029',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-glen-plaid-overshirt-prod196690153',
  // 'https://www.bloomingdales.com/shop/product/canali-kei-quilted-lining-top-coat?ID=5543205&CategoryID=1065659',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-monili-loop-shearling-lined-suede-combat-boots-prod193990105',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-botanical-guipure-short-sleeve-mini-dress-prod194420093',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-faux-pearl-eyelet-dress?ID=5399036&CategoryID=1065659',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-sleeveless-cherry-guipure-cocktail-dress?ID=5534756&CategoryID=1065659',
  // 'https://www.farfetch.com/in/shopping/men/kiton-long-sleeve-jersey-polo-shirt-item-22264260.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sequin-collar-blouse-prod198320249',
  // 'https://www.bloomingdales.com/shop/product/etro-silk-printed-maxi-shirtdress?ID=5700086&CategoryID=1065659',
  // 'https://www.farfetch.com/in/shopping/men/canali-wool-shirt-jacket-item-30849524.aspx',
  // 'https://www.bergdorfgoodman.com/p/kiton-mens-cashmere-blend-crewneck-sweater-prod198321000',
  // 'https://www.bergdorfgoodman.com/p/kiton-mens-cashmere-blend-crewneck-sweater-prod198320665',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-lace-up-herringbone-detail-hiking-boots-item-31293209.aspx',
  // 'https://www.neimanmarcus.com/p/brunello-cucinelli-stretch-silk-satin-track-trousers-prod282310099',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-cashmere-wool-flannel-wide-sartorial-pants-with-belt-prod193920054',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-stretch-silk-satin-track-trousers-prod193920101',
  // 'https://www.farfetch.com/in/shopping/men/canali-checked-wool-jacket-item-31093268.aspx',
  // 'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-merino-wool-maxi-check-overshirt-prod285600513',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-alligator-leather-buckle-belt-prod195480010', 
  // 'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-merino-wool-maxi-check-overshirt-prod196680053',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-tassel-detail-loafers-item-23689667.aspx',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-crispy-silk-chiffon-tie-blouse-prod193920006',
  // 'https://www.farfetch.com/in/shopping/men/dolce-gabbana-single-breasted-herringbone-jacket-item-20049600.aspx',
  // 'https://www.shopsimon.com/products/womens-floral-halter-tie-waist-midi-dress-in-white-black',
  // 'https://www.neimanmarcus.com/p/brunello-cucinelli-wes-textured-suede-belt-with-monili-trim-prod285250302',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-wes-textured-suede-belt-with-monili-trim-prod197550051',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-leather-monili-heel-ankle-booties-prod192080207',
  // 'https://www.bloomingdales.com/shop/product/etro-velvet-paisley-mermaid-maxi-dress?ID=5694547&CategoryID=1065659',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-glam-cable-knit-mohair-sweater-prod198320289',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-short-sleeve-drop-waist-cherry-blossom-cloque-dress?ID=5534779&CategoryID=1065659',
  // 'https://www.shopsimon.com/products/carolina-herrera-wool-blend-collarless-jacket',
  // 'https://www.shopsimon.com/products/carolina-herrera-wool-blend-single-breasted-coat',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-kent-hand-tailored-suit-jacket-prod198450594',
  // 'https://www.shopsimon.com/products/womens-ruched-long-sleeve-mini-dress-in-black',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-denta-draped-shoulder-georgette-caftan?ID=5534791&CategoryID=1065659',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-floral-embroidered-short-sleeve-dress?ID=5652445&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-guipure-asymmetric-trumpet-midi-day-dress-prod192590333',
];

// export const BEST_DEALS_LINKS_SET = [
//   'https://www.farfetch.com/in/shopping/men/dolce-gabbana-leather-messenger-bag-item-27322532.aspx',
//   // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-leather-ankle-booties-with-monili-pull-tab-prod193990109',
//   'https://www.bergdorfgoodman.com/p/brunello-cucinelli-suede-monili-heel-chelsea-booties-prod192080217',
//   // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-fluid-wool-crepe-pants-prod193930049',
//   // 'https://www.neimanmarcus.com/p/brunello-cucinelli-fluid-wool-crepe-pants-prod282310250',
//   'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-womens-handbag-2',
//   'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-shoulder-womens-bag-3',
//   'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-shoulder-womens-bag',
//   'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-shoulder-womens-bag-1',
//   'https://www.bloomingdales.com/shop/product/canali-kei-plaid-unstructured-trim-fit-sport-coat?ID=5536127&CategoryID=1065659',
//   // 'https://www.farfetch.com/in/shopping/men/kiton-linen-tapered-trousers-item-23238026.aspx',
//   'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-crew-neck-top-item-32558561.aspx',
//   'https://shop.simon.com/products/three-quarter-bateau-neck-poplin-dress-in-navy-multi?crpid=8587379605564',
//   'https://www.shopsimon.com/products/three-quarter-bateau-neck-poplin-dress-in-navy-multi',
//   'https://www.shopsimon.com/products/english-rose-jacquard-fit-and-flare-knit-dress-in-pink-blush-peony',
//   'https://www.farfetch.com/in/shopping/men/canali-zip-front-pocketed-gilet-item-30799802.aspx',
//   'https://www.bergdorfgoodman.com/p/brunello-cucinelli-striped-wool-cashmere-v-neck-sweater-prod193930026',
//   'https://www.farfetch.com/in/shopping/men/dolce-gabbana-bandana-print-shirt-item-26519066.aspx',
//   'https://www.shopsimon.com/products/carolina-herrera-off-the-shoulder-ruffled-a-line-gown',
//   'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-jewel-neck-meta-long-sleeve-gown?ID=5182114&CategoryID=1065659',
//   // 'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-short-sleeve-cutout-hem-tweed-dress?ID=5534751&CategoryID=1065659',
//   'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-short-sleeve-cutout-hem-tweed-mini-dress-with-belt-prod192590342',
//   'https://www.bloomingdales.com/shop/product/carolina-herrera-one-shoulder-column-gown?ID=5565205&CategoryID=1065659',
//   'https://www.bloomingdales.com/shop/product/canali-kei-wool-silk-linen-herringbone-unstructured-trim-fit-sport-coat?ID=5536129&CategoryID=1065659',
//   'https://www.neimanmarcus.com/p/carolina-herrera-tulip-bell-sleeve-mini-dress-prod286710021',
//   'https://www.bloomingdales.com/shop/product/carolina-herrera-flare-sleeve-shift-dress?ID=5634812&CategoryID=1065659',
//   'https://www.bergdorfgoodman.com/p/carolina-herrera-tulip-bell-sleeve-mini-dress-prod196640443',
//   'https://www.shopsimon.com/products/mens-gancini-ornament-loafer-in-black',
//   'https://www.shopsimon.com/products/long-sleeve-orchid-threadwork-embroidered-lace-cardigan-in-white-multi',
//   'https://www.bergdorfgoodman.com/p/brunello-cucinelli-felpa-buttoned-bomber-cardigan-prod198321340',
//   'https://www.farfetch.com/in/shopping/men/brioni-fine-knit-silk-cashmere-jumper-item-19600460.aspx',
//   'https://www.neimanmarcus.com/p/brunello-cucinelli-lightly-quilted-prod287440309',
//   'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cashmere-full-zip-sweater-prod285600687',
//   'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-off-the-shoulder-flower-applique-long-sleeve-knit-mini-dress-prod194420064',
//   'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-merino-wool-plaid-button-down-shirt-prod285600598',
//   'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-sleeveless-butterfly-jacquard-knit-midi-dress-prod192600073',
//   'https://shop.simon.com/products/brown-fleece-wool-long-dress?crpid=8751234613308',
//   'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-cashmere-knit-full-zip-sweater-prod281660640',
//   'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-knitted-polo-shirt-item-30413431.aspx',
//   'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-textured-jumper-item-30317981.aspx',
// ];

// Helper function to randomly select N items from an array
function selectRandomItems<T>(array: T[], count: number): T[] {
  const shuffled = shuffleArray([...array]);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

// Filter out empty strings and invalid entries
function filterActiveLinks(links: string[]): string[] {
  return links.filter(link => typeof link === 'string' && link.trim().length > 0 && !link.trim().startsWith('//'));
}

// Randomly select 8 links from BEST_DEALS_LINKS_SET
export const BEST_DEALS_LINKS = (() => {
  const activeLinks = filterActiveLinks(BEST_DEALS_LINKS_SET);
  return selectRandomItems(activeLinks, 8);
})();

// Randomly select 10 links from DESIGNER_SALE_LINKS_SET
export const DESIGNER_SALE_LINKS = (() => {
  const activeLinks = filterActiveLinks(DESIGNER_SALE_LINKS_SET);
  return selectRandomItems(activeLinks, 8);
})();