// /**
//  * Curated product links for each section of the landing page.
//  * These links are fetched from the backend and displayed in the exact order specified.
//  */

// export const DESIGNER_SALE_LINKS = [
//   'https://www.harrods.com/en-gb/p/tom-ford-suede-jacket-00000000000774607',
//   'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-hooded-puffer-jacket-item-30651864.aspx',
//   'https://www.ssense.com/en-in/men/product/zegna/yellow-calfskin-suede-jacket/19219661',
//   'https://www.harrods.com/en-gb/p/ralph-lauren-purple-label-wool-cashmere-ripley-jacket-000000000007801528',
//   'https://www.ssense.com/en-in/men/product/valentino/navy-and-beige-le-chat-de-la-maison-patch-bomber-jacket/17863731',
//   'https://www.harrods.com/en-gb/p/brioni-cotton-cashmere-shirt-000000000007449750',
//   'https://www.ssense.com/en-in/men/product/zegna/beige-deconstructed-jacket/19219611',
//   'https://www.harrods.com/en-gb/p/valentino-embellished-denim-jacket-000000000007788887',
//   'https://www.farfetch.com/in/shopping/men/brioni-zip-fastening-hoodie-item-31982549.aspx',
//   'https://www.harrods.com/en-gb/p/polo-ralph-lauren-shearling-aviator-jacket-000000000007699678',
// ];

// export const NEW_THIS_WEEK_LINKS = [
//   'https://www.farfetch.com/in/shopping/men/brioni-ribbed-sleeve-suede-bomber-jacket-item-31906754.aspx?storeid=10704',
//   'https://www.harrods.com/en-gb/p/tom-ford-denim-jacket-000000000007861264',
//   'https://www.farfetch.com/in/shopping/women/etro-floral-print-midi-dress-item-22582044.aspx?storeid=9893',
//   'https://www.ssense.com/en-in/men/product/salvatore-ferragamo/brown-trench-car-coat/17935481',
//   'https://shop.simon.com/products/mens-single-button-suit-jacket-in-black?crpid=8725214560316',
//   'https://www.farfetch.com/in/shopping/women/zimmermann-ascension-mini-dress-item-30159585.aspx?storeid=9672',
//   'https://shop.simon.com/products/womens-floral-halter-tie-waist-midi-dress-in-white-black?crpid=8700537962556',
//   'https://www.bloomingdales.com/shop/product/lanvin-long-wool-peacoat?ID=5811554&CategoryID=1001174#SORTBY/PRICE_HIGH_TO_LOW',
//   'https://shop.simon.com/products/sunflower-fil-coupe-cocktail-dress-in-yellow?crpid=8721414062140',
//   'https://www.ssense.com/en-in/women/product/givenchy/beige-large-collar-shearling-jacket/14752821',
//   'https://shop.simon.com/products/womens-leather-jacket-in-black?crpid=8730755989564',
//   'https://www.ssense.com/en-in/women/product/valentino/blue-embroidered-crepe-couture-minidress/17227571',
//   'https://www.harrods.com/en-gb/p/canali-wool-2-piece-suit-000000000007831326',
//   'https://www.farfetch.com/in/shopping/men/kiton-corduroy-effect-jacket-item-32486684.aspx?storeid=14922',
//   'https://www.harrods.com/en-gb/p/mackage-down-leather-trim-parka-000000000007644737',
//   'https://www.farfetch.com/in/shopping/women/zimmermann-floral-print-dress-item-29850715.aspx?storeid=9918',
//   'https://shop.simon.com/products/bally-6305469-mens-marine-blue-sheep-shearling-winter-coat-size-48-m?crpid=7870209327164',
//   'https://www.harrods.com/en-gb/p/tom-ford-wool-silk-ribbed-sweater-000000000007746142',
//   'https://shop.simon.com/products/tinted-sequined-turtleneck-sweater-in-black?crpid=8725375418428',
//   'https://www.bloomingdales.com/shop/product/balmain-color-block-monogram-jacket?ID=5550562&CategoryID=1001174#PAGEINDEX,SORTBY/2,PRICE_HIGH_TO_LOW',
// ];

// export const LUXURY_CURATED_LINKS = [
//   'https://shop.simon.com/products/womens-natural-liftoff-midi-dress-in-blue?crpid=7941200969788',
//   'https://www.harrods.com/en-gb/p/valentino-tweed-embellished-mini-dress-000000000007789397',
//   'https://www.ssense.com/en-in/women/product/tom-ford/gold-one-shoulder-twist-front-evening-maxi-dress/17721721',
//   'https://www.bloomingdales.com/shop/product/carolina-herrera-brocade-dress?ID=5565462&CategoryID=1006738#SORTBY/PRICE_HIGH_TO_LOW',
// ];

// export const BEST_DEALS_LINKS = [
//   'https://www.farfetch.com/in/shopping/women/elie-saab-bead-embellished-gown-item-31921473.aspx?storeid=13676',
//   'https://shop.simon.com/products/bally-6302043-mens-militi-brown-leather-coat?crpid=7926646341692',
//   'https://www.ssense.com/en-in/women/product/givenchy/black-cropped-cocoon-leather-biker-jacket/18115411',
//   'https://www.farfetch.com/in/shopping/men/brioni-leather-sahariana-jacket-item-24861252.aspx?storeid=10704',
//   'https://www.bloomingdales.com/shop/product/burberry-leather-bomber-jacket?ID=5885136&CategoryID=1001174#SORTBY/PRICE_HIGH_TO_LOW',
//   'https://www.farfetch.com/in/shopping/women/valentino-garavani-floral-lace-detail-dresswide-item-11912847.aspx?storeid=9728',
//   'https://www.ssense.com/en-in/women/product/balmain/black-tweed-and-leather-bomber-jacket/17952381',
//   'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-quilted-shearling-detail-coat-item-31812631.aspx?storeid=16981',
//   'https://www.bloomingdales.com/shop/product/lanvin-oversized-wool-pea-coat?ID=5811550&CategoryID=1001174#PAGEINDEX,SORTBY/2,PRICE_HIGH_TO_LOW',
//   'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-double-breasted-jacket-item-30317997.aspx',
//   'https://www.ssense.com/en-in/women/product/rick-owens/gray-concordians-exploder-reversible-shearling-jacket/17880561',
//   'https://www.farfetch.com/in/shopping/women/tom-ford-crystal-embellished-maxi-dress-item-30023211.aspx?storeid=17405',
//   'https://www.farfetch.com/in/shopping/men/brioni-embossed-leather-jacket-item-23939842.aspx?storeid=12067',
//   'https://shop.simon.com/products/floral-printed-asymmetric-pleated-dress-in-multi?crpid=8701898817596',
//   'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-leather-jacket-item-30046309.aspx',
//   'https://www.bloomingdales.com/shop/product/polo-ralph-lauren-the-polo-coat?ID=4699532&CategoryID=1001174#PAGEINDEX,SORTBY/2,PRICE_HIGH_TO_LOW',
//   'https://www.farfetch.com/in/shopping/men/kiton-padded-cashmere-blend-coat-item-22338794.aspx?storeid=10568',
//   'https://shop.simon.com/products/textured-nappa-leather-coat-in-black?crpid=8728268374076',
//   'https://www.farfetch.com/in/shopping/women/oscar-de-la-renta-bow-embellished-silk-halterneck-gown-item-19029702.aspx?storeid=11092',
//   'https://www.farfetch.com/in/shopping/men/tom-ford-zip-front-leather-jacket-item-30753896.aspx?storeid=9774',
// ];
export const DESIGNER_SALE_LINKS = [
 
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-belted-leather-safari-jacket-item-31293216.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-hooded-jacket-item-30413413.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brioni-double-breasted-leather-jacket-item-31942866.aspx',
  // 'https://www.farfetch.com/in/shopping/men/kiton-double-breasted-cashmere-coat-item-15926065.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brioni-suede-jacket-item-24587446.aspx',
  
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-belt-waist-shirt-jacket-item-31783300.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-shearling-lined-button-front-parka-prod194070160',
  // 'https://www.neimanmarcus.com/p/brunello-cucinelli-cashmere-opera-p-prod287450039',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-cashmere-coat-with-removable-sheep-shearling-liner-and-collar-prod193920097',
  // 'https://www.farfetch.com/in/shopping/men/kiton-pinstripe-suit-item-30081063.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-silk-tuxedo-suit-item-22291842.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brioni-zip-fastening-ribbed-cardigan-item-32557412.aspx',
  // 'https://www.farfetch.com/in/shopping/men/kiton-quilted-detachable-hood-coat-item-31133563.aspx',
  
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-double-breasted-jacket-item-30317997.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-cashmere-coat-item-30298005.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-tartan-organza-paillette-knit-double-breasted-blazer-prod193920051',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-suede-jacket-item-30296986.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-silk-organza-all-over-pailet-prod193920276',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-paillette-crocco-effect-mohair-double-breasted-overcoat-prod193920017',
  // 'https://www.farfetch.com/in/shopping/men/kiton-hybrid-hooded-puffer-jacket-item-18626619.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-striped-suit-item-26675150.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-ribbed-knit-suede-jacket-item-30918339.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-belted-jacket-item-30788020.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-chevron-raglan-sleeve-overcoat-prod194070179',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-capretta-lamb-shearling-belted-vest-prod193920146',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-embellished-long-sleeve-trumpet-gown-prod196640313',
  // 'https://www.neimanmarcus.com/p/carolina-herrera-floral-embroidered-strapless-drop-waist-dress-prod284850079',
  // 'https://www.neimanmarcus.com/p/carolina-herrera-embellished-long-sleeve-trumpet-gown-prod284850083',
  // 'https://www.farfetch.com/in/shopping/men/kiton-single-breasted-cashmere-coat-item-20902227.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-quilted-high-neck-jacket-item-30972276.aspx',
  // 'https://www.farfetch.com/in/shopping/men/kiton-double-breasted-cashmere-coat-item-31907174.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-suede-full-zip-jacket-with-chest-zips-prod197320103',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-leather-full-zip-bomber-jacket-with-chest-zips-prod198321381',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-herringbone-pattern-double-breasted-coat-item-24059163.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-leather-biker-jacket-with-removable-shearling-collar-prod193920023',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-cable-knit-padded-jacket-item-20239078.aspx',
  // 'https://www.bergdorfgoodman.com/p/kiton-mens-super-160s-tonal-micro-stripe-suit-prod190750021',
  // 'https://www.neimanmarcus.com/p/carolina-herrera-3d-floral-embellished-strapless-column-gown-prod284850065',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-ribbed-knit-wool-bomber-jacket-item-31181408.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-shawl-collar-cardigan-item-31926042.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-cashmere-military-jacket-item-30787270.aspx',
  // 'https://www.neimanmarcus.com/p/brunello-cucinelli-mock-neck-nordic-cashmere-sweater-prod282250998',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-classic-fitted-blazer-item-14111133.aspx',
  // 'https://www.neimanmarcus.com/p/brunello-cucinelli-suede-button-fro-prod287440096',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-fine-ribbed-blazer-item-30651884.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-shawl-collar-double-breasted-cardigan-item-31401348.aspx',
  // 'https://www.farfetch.com/in/shopping/men/brioni-embossed-leather-jacket-item-23939842.aspx',
  // 'https://www.neimanmarcus.com/p/carolina-herrera-plunging-halter-pleated-drop-waist-gown-prod284930082',
  // 'https://www.farfetch.com/in/shopping/men/kiton-kired-penna-reversible-jacket-item-31132965.aspx',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mens-donegal-chalk-stripe-two-piece-suit-prod195800047',
];

export const NEW_THIS_WEEK_LINKS = [
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-kent-hand-tailored-velvet-jacket-prod285470384',
 
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-suede-overshirt-prod282630097',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-shoulder-womens-bag-4',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-womens-handbag',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-silk-satin-button-down-shirt-prod193920258',
  
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cotton-velvet-shawl-lapel-sport-coat-prod285600538',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-textured-wool-notch-lapel-sport-coat-prod194790326',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-brushed-cashmere-twill-blazer-prod285600690',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-gregory-hand-tailored-velvet-dinner-jacket-prod285470192','https://www.bergdorfgoodman.com/p/brunello-cucinelli-wool-flannel-wide-leg-ankle-cargo-pants-prod193920181',
  'https://www.neimanmarcus.com/p/givenchy-bow-draped-mini-t-shirt-dress-prod282780964',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-silk-satin-button-down-shirt-prod282310146',
  'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-leather-boots-item-23688718.aspx',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-embellished-button-dress?ID=5634850&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-crystal-button-front-tweed-midi-dress-with-belt-prod196640370',
  'https://www.neimanmarcus.com/p/carolina-herrera-crystal-button-front-tweed-midi-dress-with-belt-prod284810191',
  'https://www.bergdorfgoodman.com/p/kiton-mens-baba-cotton-and-silk-side-pocket-overshirt-prod193330109',
  'https://www.farfetch.com/in/shopping/men/brioni-suede-loafers-item-29083290.aspx',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-cutout-embroidered-tweed-mini-dress-prod192590354',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-cherry-blossom-jacquard-ombre-dress-prod192590366',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-crystal-embroidered-short-sleeve-mini-cocktail-dress-prod192600084',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-butterfly-faille-bustier-tea-length-dress-prod192590344',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-single-breasted-linen-blazer-item-23608291.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-metallic-double-pocket-blouse-prod198320210',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-monili-fan-earrings-prod193920125',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-logo-embossed-messenger-bag-item-28450299.aspx',
  'https://www.farfetch.com/in/shopping/men/canali-single-breasted-blazer-item-25708437.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-felpa-jersey-safari-jacket-prod198320302',
  'https://www.bergdorfgoodman.com/p/kiton-printed-silk-midi-shirtdress-prod193900314',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-tiered-multi-strand-drop-earrings-prod279610256',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-felpa-jersey-safari-jacket-prod282251100',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-one-shoulder-silk-drape-dress?ID=5652420&CategoryID=1065659',
  'https://www.shopsimon.com/products/wanda-mini-stain-and-strass-top-handle-bag',
  'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-cotton-zip-up-hoodie-item-31433795.aspx',
  'https://www.shopsimon.com/products/wanda-mini-stain-and-strass-top-handle-bag-1',
  'https://www.harrods.com/en-gb/p/valentino-wool-silk-leopard-tie-mini-dress-000000000007789264',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-stretch-satin-button-front-blouse-prod282280051',
  'https://www.shopsimon.com/products/salvatore-ferragamo-leather-shoulder-womens-bag-1',
  'https://www.bloomingdales.com/shop/product/canali-siena-screenweave-solid-regular-fit-suit?ID=5147244&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/canali-siena-screenweave-regular-fit-suit?ID=5442099&CategoryID=1065659',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-logo-plaque-shoulder-bag-item-19172297.aspx',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-buttoned-cardigan-item-31984028.aspx',
  'https://www.farfetch.com/in/shopping/men/canali-checked-blazer-item-27816109.aspx',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-ribbed-knit-cotton-polo-shirt-item-22057127.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mohair-cozy-candy-floss-knit-crewneck-sweater-prod193920045',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-metallic-cashmere-silk-mock-neck-top-prod285280338',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sparkling-cashmere-winter-vanise-crewneck-sweater-prod193920011',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sequined-english-rib-sweater-prod192250092',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-sparkly-zip-jacket-prod282310098',
];

export const LUXURY_CURATED_LINKS = [
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sparkly-zip-jacket-prod193920114',
  // 'https://www.harrods.com/en-gb/p/valentino-wool-silk-bow-embellished-mini-dress-000000000007789224',
  // 'https://www.neimanmarcus.com/p/brunello-cucinelli-cashmere-turtlen-prod287450130',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-mat-leather-equestrian-riding-boots-prod193990110',
  // 'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cashmere-glen-plaid-overshirt-prod285600668',
  // 'https://www.bloomingdales.com/shop/product/canali-kei-wool-silk-donegal-quilted-lining-top-coat?ID=5543202&CategoryID=1065659',
  // 'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-superfine-nylon-snap-front-quilted-vest-prod196690029',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-cashmere-glen-plaid-overshirt-prod196690153',
  // 'https://www.bloomingdales.com/shop/product/canali-kei-quilted-lining-top-coat?ID=5543205&CategoryID=1065659',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-monili-loop-shearling-lined-suede-combat-boots-prod193990105',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-botanical-guipure-short-sleeve-mini-dress-prod194420093',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-faux-pearl-eyelet-dress?ID=5399036&CategoryID=1065659',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-sleeveless-cherry-guipure-cocktail-dress?ID=5534756&CategoryID=1065659',
  // 'https://www.farfetch.com/in/shopping/men/kiton-long-sleeve-jersey-polo-shirt-item-22264260.aspx',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-sequin-collar-blouse-prod198320249',
  // 'https://www.bloomingdales.com/shop/product/etro-silk-printed-maxi-shirtdress?ID=5700086&CategoryID=1065659',
  // 'https://www.farfetch.com/in/shopping/men/canali-wool-shirt-jacket-item-30849524.aspx',
  //  'https://www.ssense.com/en-us/men/product/valentino/beige-check-pattern-single-breasted-cotton-blazer/17863501',
  // 'https://www.bergdorfgoodman.com/p/kiton-mens-cashmere-blend-crewneck-sweater-prod198321000',
  // 'https://www.bergdorfgoodman.com/p/kiton-mens-cashmere-blend-crewneck-sweater-prod198320665',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-lace-up-herringbone-detail-hiking-boots-item-31293209.aspx',
  // 'https://www.neimanmarcus.com/p/brunello-cucinelli-stretch-silk-satin-track-trousers-prod282310099',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-cashmere-wool-flannel-wide-sartorial-pants-with-belt-prod193920054',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-stretch-silk-satin-track-trousers-prod193920101',
  // 'https://www.farfetch.com/in/shopping/men/canali-checked-wool-jacket-item-31093268.aspx',
  // 'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-merino-wool-maxi-check-overshirt-prod285600513',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-alligator-leather-buckle-belt-prod195480010',
  // 'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-merino-wool-maxi-check-overshirt-prod196680053',
  // 'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-tassel-detail-loafers-item-23689667.aspx',
  // 'https://www.bergdorfgoodman.com/p/givenchy-barrel-leg-denim-jumpsuit-prod193540081',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-crispy-silk-chiffon-tie-blouse-prod193920006',
  // 'https://www.bergdorfgoodman.com/p/givenchy-cocoon-cropped-utility-jacket-prod193540062',
  // 'https://www.bergdorfgoodman.com/p/givenchy-square-neck-sleeveless-ruffle-fluted-mini-dress-prod193530061',
  // 'https://www.farfetch.com/in/shopping/men/dolce-gabbana-single-breasted-herringbone-jacket-item-20049600.aspx',
  // 'https://www.shopsimon.com/products/womens-floral-halter-tie-waist-midi-dress-in-white-black',
  // 'https://www.neimanmarcus.com/p/brunello-cucinelli-wes-textured-suede-belt-with-monili-trim-prod285250302',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-wes-textured-suede-belt-with-monili-trim-prod197550051',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-leather-monili-heel-ankle-booties-prod192080207',
  // 'https://www.bloomingdales.com/shop/product/etro-velvet-paisley-mermaid-maxi-dress?ID=5694547&CategoryID=1065659',
  // 'https://www.bergdorfgoodman.com/p/givenchy-sleeveless-mock-neck-midi-dress-prod194950197',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-glam-cable-knit-mohair-sweater-prod198320289',
  // 'https://www.neimanmarcus.com/p/givenchy-sleeveless-mock-neck-midi-dress-prod282780837',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-short-sleeve-drop-waist-cherry-blossom-cloque-dress?ID=5534779&CategoryID=1065659',
  // 'https://www.shopsimon.com/products/carolina-herrera-wool-blend-collarless-jacket',
  // 'https://www.shopsimon.com/products/carolina-herrera-wool-blend-single-breasted-coat',
  'https://www.bergdorfgoodman.com/p/ralph-lauren-purple-label-mens-kent-hand-tailored-suit-jacket-prod198450594',
  // 'https://www.shopsimon.com/products/womens-ruched-long-sleeve-mini-dress-in-black',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-denta-draped-shoulder-georgette-caftan?ID=5534791&CategoryID=1065659',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-floral-embroidered-short-sleeve-dress?ID=5652445&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-guipure-asymmetric-trumpet-midi-day-dress-prod192590333',
];

export const BEST_DEALS_LINKS = [
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-leather-messenger-bag-item-27322532.aspx',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-leather-ankle-booties-with-monili-pull-tab-prod193990109',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-suede-monili-heel-chelsea-booties-prod192080217',
  // 'https://www.bergdorfgoodman.com/p/brunello-cucinelli-fluid-wool-crepe-pants-prod193930049',
  // 'https://www.neimanmarcus.com/p/brunello-cucinelli-fluid-wool-crepe-pants-prod282310250',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-womens-handbag-2',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-shoulder-womens-bag-3',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-shoulder-womens-bag',
  'https://www.shopsimon.com/products/salvatore-ferragamo-fabric-shoulder-womens-bag-1',
  'https://www.bloomingdales.com/shop/product/canali-kei-plaid-unstructured-trim-fit-sport-coat?ID=5536127&CategoryID=1065659',
  // 'https://www.ssense.com/en-in/women/product/valentino/black-scoop-minidress/12290751',
  // 'https://www.farfetch.com/in/shopping/men/kiton-linen-tapered-trousers-item-23238026.aspx',
  'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-crew-neck-top-item-32558561.aspx',
  'https://shop.simon.com/products/three-quarter-bateau-neck-poplin-dress-in-navy-multi?crpid=8587379605564',
  'https://www.shopsimon.com/products/three-quarter-bateau-neck-poplin-dress-in-navy-multi',
  'https://www.shopsimon.com/products/english-rose-jacquard-fit-and-flare-knit-dress-in-pink-blush-peony',
  'https://www.farfetch.com/in/shopping/men/canali-zip-front-pocketed-gilet-item-30799802.aspx',
  'https://www.bergdorfgoodman.com/p/givenchy-short-sleeve-patch-pocket-mini-cocoon-dress-prod193530044',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-striped-wool-cashmere-v-neck-sweater-prod193930026',
  'https://www.neimanmarcus.com/p/givenchy-cotton-twill-herringbone-mini-dress-prod282780856',
  'https://www.farfetch.com/in/shopping/men/dolce-gabbana-bandana-print-shirt-item-26519066.aspx',
  'https://www.shopsimon.com/products/carolina-herrera-off-the-shoulder-ruffled-a-line-gown',
  'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-jewel-neck-meta-long-sleeve-gown?ID=5182114&CategoryID=1065659',
  // 'https://www.bloomingdales.com/shop/product/oscar-de-la-renta-short-sleeve-cutout-hem-tweed-dress?ID=5534751&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-short-sleeve-cutout-hem-tweed-mini-dress-with-belt-prod192590342',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-one-shoulder-column-gown?ID=5565205&CategoryID=1065659',
  'https://www.bloomingdales.com/shop/product/canali-kei-wool-silk-linen-herringbone-unstructured-trim-fit-sport-coat?ID=5536129&CategoryID=1065659',
  'https://www.neimanmarcus.com/p/carolina-herrera-tulip-bell-sleeve-mini-dress-prod286710021',
  'https://www.bloomingdales.com/shop/product/carolina-herrera-flare-sleeve-shift-dress?ID=5634812&CategoryID=1065659',
  'https://www.bergdorfgoodman.com/p/carolina-herrera-tulip-bell-sleeve-mini-dress-prod196640443',
  // 'https://www.farfetch.com/in/shopping/men/givenchy-logo-print-cotton-hoodie-sweatshirt-item-19948342.aspx',
  'https://www.shopsimon.com/products/mens-gancini-ornament-loafer-in-black',
  'https://www.shopsimon.com/products/long-sleeve-orchid-threadwork-embroidered-lace-cardigan-in-white-multi',
  'https://www.farfetch.com/in/shopping/men/givenchy-g-trail-backpack-item-24191664.aspx',
  'https://www.harrods.com/en-gb/p/valentino-wool-cotton-blazer-000000000007788846',
  'https://www.ssense.com/en-in/women/product/valentino/navy-plusdepois-print-bow-jacket/17735691',
  'https://www.bergdorfgoodman.com/p/brunello-cucinelli-felpa-buttoned-bomber-cardigan-prod198321340',
  'https://www.farfetch.com/in/shopping/men/brioni-fine-knit-silk-cashmere-jumper-item-19600460.aspx',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-lightly-quilted-prod287440309',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-cashmere-full-zip-sweater-prod285600687',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-off-the-shoulder-flower-applique-long-sleeve-knit-mini-dress-prod194420064',
  'https://www.neimanmarcus.com/p/ralph-lauren-purple-label-mens-merino-wool-plaid-button-down-shirt-prod285600598',
  'https://www.bergdorfgoodman.com/p/oscar-de-la-renta-sleeveless-butterfly-jacquard-knit-midi-dress-prod192600073',
  'https://shop.simon.com/products/brown-fleece-wool-long-dress?crpid=8751234613308',
  'https://www.neimanmarcus.com/p/brunello-cucinelli-mens-cashmere-knit-full-zip-sweater-prod281660640',
  'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-knitted-polo-shirt-item-30413431.aspx',
  'https://www.farfetch.com/in/shopping/men/brunello-cucinelli-textured-jumper-item-30317981.aspx',
  'https://www.harrods.com/en-gb/p/valentino-wool-silk-embroidered-jacket-000000000007764710',
  'https://www.harrods.com/en-gb/p/valentino-wool-silk-embellished-mini-dress-000000000007789374',
  'https://www.harrods.com/en-gb/p/valentino-wool-silk-embellished-mini-dress-000000000007789250',
];
